### ISSUE TITLE
ImportError:libpcl_helper.so: undefined symbol: _ZN3pcl6search6KdTreeINS_11PointXYZRGBEEC1Eb

### ISSUE THREAD

**Issue by dingxiaoliang33** [lpltk/pydriver#3]
Hello,
I'm very exciting to use this project but I cannot run the example. Could you help me.

I followed the installation steps, except one step of the PCL installation, because for my version of 

Ubuntu(15.04), libpcl-all library does not exist in this PPA, so I build from source instead.

[http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php]

All seem to be in /usr/include/pcl-1.7 and /usr/local/include/pcl-1.7.( version 1.7.2)

when I run the example ,a problem has bean encountered.

```
python kitti_usage.py
Traceback (most recent call last):
  File "kitti_usage.py", line 12, in <module>
    import pydriver
  File "/usr/local/lib/python2.7/dist-packages/pydriver/__init__.py", line 52, in <module>
    from . import features
  File "/usr/local/lib/python2.7/dist-packages/pydriver/features/__init__.py", line 15, in <module>
    from .base import FeatureExtractor  # base class
  File "pydriver/pcl/pcl.pxd", line 11, in init pydriver.features.base (build_c/pydriver/features/base.cpp:18142)
  File "/usr/local/lib/python2.7/dist-packages/pydriver/pcl/__init__.py", line 18, in <module>
    from .pcl import PCLHelper
ImportError: /usr/local/lib/python2.7/dist-packages/pydriver/pcl/pcl_helper/lib/libpcl_helper.so: undefined symbol: _ZN3pcl6search6KdTreeINS_11PointXYZRGBEEC1Eb
```

What can I do to solve this problem? I really need this module to work and I will appreciate if you can help me.
Thank !!

**Comment by Leonard-Plotkin** [comment]
Hello dingxiaoliang33,

the correct compilation of PCL with all required modules is a somewhat troublesome process. The likely reason for your problem is that PCL was compiled without KdTree, possibly because of missing dependencies or missing values in the CMake configuration.

However, a quick search suggests that there should be some ready-to-use packages for Ubuntu 15.04 (Vivid Vervet) which you can find here:
https://launchpad.net/ubuntu/vivid/+source/pcl

There seems to be no package "libpcl-all" anymore, but I would suggest to try to install the package named "libpcl1.7" and/or "libpcl-dev".

To avoid further problems I recommend to delete the files produced by the unsuccessful build of PyDriver/PCLHelper using "make clean" before trying to compile it again after correct installation of PCL.

If the problem persists I would advice to also pose the question about correct compilation of PCL including KdTree on Ubuntu 15.04 in PCL support groups.

Best Regards,
Leonard

**Comment by dingxiaoliang33** [comment]
Thanks for your advice!
I have compile Point Cloud Library (PCL) from source completely, including KdTree.  Then Earlier problems no longer appear.  Unfortunately when I run the example ,I still got a problem，
```
python kitti_usage.py 
Learning...
Traceback (most recent call last):
  File "kitti_usage.py", line 120, in <module>
    detector.learn(nStorageMaxRandomSamples=25000)
  File "pydriver/detectors/detectors.pyx", line 148, in pydriver.detectors.detectors.Detector.learn (build_c/pydriver/detectors/detectors.cpp:5456)
  File "pydriver/detectors/vocabularies.pyx", line 531, in pydriver.detectors.vocabularies.Vocabulary.prepareForRecognition (build_c/pydriver/detectors/vocabularies.cpp:11568)
RuntimeError: Can't prepare for recognition if empty.
```
Can you tell me what is causing this problem?
Thank!

**Comment by dingxiaoliang33** [comment]
Thanks for your advice!
I compile  PCL source completely and the example can run without error.
However I still have a question, I find the example's result is a figure, evaluating detection performance, But I don't know what is the meaning of precision and orientation .
Then  I want to reach the effect which is displayed in the home page, a car  surrounded by vectors.
So I  set VISUALIZE3D =True. Detection visualization has many different lengths of the rectangle and different colors likes white red yellow. I also don't know the different color' very clear.Could you tell me?
looking forward to your reply.
Thanks again!

**Comment by Leonard-Plotkin** [comment]
For general meaning of precision, please see https://en.wikipedia.org/wiki/Precision_and_recall

For exact definitions of "average precision" (AP) and "average orientation similarity" (AOS) as defined by the authors of the KITTI dataset, please refer to their publication "Are we ready for Autonomous Driving? The KITTI Vision Benchmark Suite" available at:
http://www.cvlibs.net/publications/Geiger2012CVPR.pdf

More information regarding visualization in PyDriver - particulary for the functions setDetectionsVisualization() and visualizeDetections() - can be found in the documented source code at:
https://github.com/lpltk/pydriver/blob/master/pydriver/pcl/pcl.pyx
