### ISSUE TITLE
Ground plane could not be processed, is the cloud empty in the expected ground viewport?

### ISSUE THREAD

**Issue by Dr-LingyunXu** [lpltk/pydriver#4]
Hello, I am trying to apply the pydriver for the object detection test, after the installation, and follow the usage instruction, i meet the following problem,

`
Training on frame 0...

---

ValueError                                Traceback (most recent call last)
<ipython-input-137-69a6bb7de8b6> in <module>()
      8     print('Training on frame %d...' % frame['frameId'])
      9     # reconstruct scene
---> 10     scene = preprocessor.process(frame)
     11     # get keypoints
     12     keypointCloud = keypointExtractor.getKeypointCloud(scene)

/usr/local/lib/python2.7/dist-packages/pydriver-1.0.2.dev2+37f3d2b-py2.7-linux-x86_64.egg/pydriver/preprocessing/preprocessing.pyx in pydriver.preprocessing.preprocessing.Preprocessor.process (build_c/pydriver/preprocessing/preprocessing.cpp:3297)()
    104         # apply cloud processors
    105         for processor in self.processors:
--> 106             processor.process(scene)
    107 
    108         # cache scene if cache is configured

/usr/local/lib/python2.7/dist-packages/pydriver-1.0.2.dev2+37f3d2b-py2.7-linux-x86_64.egg/pydriver/preprocessing/preprocessing.pyx in pydriver.preprocessing.preprocessing.GroundPlaneProcessor.process (build_c/pydriver/preprocessing/preprocessing.cpp:6850)()
    348         if cloudDetection.getCloudSize()[0] < 10:
    349             # invalid input, e.g. empty cloud
--> 350             raise ValueError("Ground plane could not be processed, is the cloud empty in the expected ground viewport?")
    351 
    352         # detect ground plane

ValueError: Ground plane could not be processed, is the cloud empty in the expected ground viewport?

`

**Comment by Leonard-Plotkin** [comment]
Hello maxtom,

this error arises when the used point cloud - either read from dataset (e.g. LIDAR data) or reconstructed from the stereo camera views - has very few points (<10) or no points at all in the area where the ground plane is expected. If you're using the original KITTI dataset (including LIDAR data), original kitti_usage.py file without any modifications and if you have set the PATH_TO_KITTI variable correctly, this definitely shouldn't happen.

In case you made modifications to the example code or are using PyDriver with a different dataset, I can merely provide some background information and suggestions how to track down the problem.

Background:
Since a moving car is subject to rotations around all axes (e.g. due to bumps on road), the view captured by its sensors is unsteady. To compensate for this effect the ground plane around the car is estimated and the view is normalized relative to this estimation. This happens in GroundPlaneProcessor in pydriver/preprocessing/preprocessing.pyx and this processor is part of the default preprocessing pipeline. You can deactivate it by changing the line 37 in kitti_usage.py to:
preprocessor = pydriver.preprocessing.Preprocessor(reconstructor, processors=())

You can also try to adjust the GroundPlaneProcessor parameters if some kind of "ground plane" is present in your data but is located not in the area expected by default. Please see the documentation of GroundPlaneProcessor in preprocessing.pyx for more information.

Debugging suggestions:
You can visualize the point cloud using the visualize() function to check whether it was read / reconstructed correctly. The best place for this check would be before line 105 in preprocessing.pyx. The cloud is in scene["cloud"] at this point. Please note, that the default viewing direction is adjusted to KITTI dataset and its coordinate system. If you're using some other data, the visible point cloud could be above or behind you, for example, so you will have to look in different directions using the mouse. It could also look very small or very large. If the point cloud looks right, try extracting the part of it which is used by GroundPlaneProcessor using the restrictViewport() function and check the visualization again whether the ground is still visible there.

If the problem persists, please let me know which dataset you're using, whether you changed any settings in the example code and whether you could successfully visualize the point cloud stored in scene["cloud"].

Kind regards,
Leonard
