### ISSUE TITLE
Alpha value calculation

### ISSUE THREAD

**Issue by kminemur** [lpltk/pydriver#5]
Thank you for sharing your works.
I'm looking for alpha value calculation for orientation evaluation.

In pydriver/pydriver/datasets/kitti.py, you have

     if includeAlpha:
          # set to object orientation
          alpha = label['box3D']['rotation_y']
          # adjust to X/Z observation angle of object center
          alpha -= -math.atan2(label['box3D']['location']['z'], label['box3D']['location']['x']) - 1.5*math.pi
          # wrap to +/-Pi
          alpha = pyNormalizeAngle(alpha)
            # convert to string
            alpha = '%.2f' % alpha

Where does "1.5*math.pi" come from?

**Comment by Leonard-Plotkin** [comment]
Hi kzkmnmr, thank you for your interest in my work. It's been quite a while since I worked on that code, but on the first glance it seems to be just a conversion between coordinate systems. The question is, how a zero degrees observation angle is defined in KITTI. The code suggests that there is a rotation about 270° (or 90° in the opposite direction) with respect to the calcuations above.

**Comment by kminemur** [comment]
Thank you very much for about the alpha calculation.
